### ISSUE TITLE
Error: characters are not allowed at line

### ISSUE THREAD

**Issue by wout** [hugopl/version_from_shard#1] opened 2022-12-30 11:37 UTC
I'm using your fzy lib in a Lucky app and often my deploys fail with the following error:

```
In lib/version_from_shard/src/version_from_shard.cr:3:8

 3 | {{ run("./extract_version", dir) }}
        ^--
Error: Error executing run (exit code: 1): ./extract_version ''


stderr:

    Error reading shard.yml: ���%�	6�=Ϫ�control characters are not allowed at line
```

Sometimes it works, other times not, and I can't figure out why.

**Comment by hugopl** [comment] 2022-12-30 20:12
hmmm for some reason it didn’t find your shard.yml file, so its passing an empty string to the extract_version script. Do this always happen with lucky apps? I mean… do you have ant suggestion about how to reproduce this issue?

**Comment by wout** [comment] 2022-12-31 09:20
So far, I haven't found a pattern in the errors. It only happens on deploys, but not consistently. I'm deploying to a docker swarm server using a multi-stage build process. It could be that the shard.yml isn't available in one of the build steps. And maybe when it doesn't fail, it's due to caching? I don't know.

I'm now using another fuzzy search lib because I needed to deploy some changes, but I would prefer yours.

**Comment by hugopl** [comment] 2023-01-02 17:09
I thought in the past about remove this dependency, but got no reasons to do so, I think this bug report can be the reason I was looking for.

version_from_shard shard maybe is more useful for apps, not libraries, since if two or more libraries depend on different versions of it the dependency can cause problems.

I'll release a new version of fzy without this dependency then close this issue.

Thanks for the report.

**Comment by hugopl** [comment] 2023-01-02 17:41
Fixed by https://github.com/hugopl/fzy/releases/tag/v0.5.4

**Closed as completed by hugopl** 2023-01-02 17:41 UTC
Labels: bug

**Comment by hugopl** [comment] 2023-01-02 17:43
In fact it was not really fixed, hehehe, since I can't know the cause of the issue without looking how the deploy is being made.
